export const NPMRC = '.npmrc'
export const PACKAGE_JSON = 'package.json'
export const PNPM_WORKSPACE_YAML = 'pnpm-workspace.yaml'

/**
 * Default indent: 2 spaces
 */
export const DEFAULT_INDENT = 2

/**
 * @see {@link https://pnpm.io/10.x/settings}
 * @see {@link https://pnpm.io/settings}
 * Documented pnpm config fields that can be migrated from `.npmrc`.
 *
 * Intentionally excluded workspace manifest-only fields:
 * - `catalog`
 * - `catalogMode`
 * - `catalogs`
 * - `cleanupUnusedCatalogs`
 * - `packages`
 */
// @keep-sorted
// @keep-unique
export const PNPM_SETTINGS_FIELDS: string[] = [
  'allowBuilds',
  'allowedDeprecatedVersions',
  'allowNonAppliedPatches',
  'allowUnusedPatches',
  'audit',
  'auditConfig',
  'autoInstallPeers',
  'blockExoticSubdeps',
  'cacheDir',
  'childConcurrency',
  'ci',
  'color',
  'configDependencies',
  'dangerouslyAllowAllBuilds',
  'dedupeDirectDeps',
  'dedupeInjectedDeps',
  'dedupePeerDependents',
  'dedupePeers',
  'deployAllFiles',
  'disallowWorkspaceCycles',
  'dlxCacheMaxAge',
  'enableGlobalVirtualStore',
  'enableModulesDir',
  'enablePrePostScripts',
  'engineStrict',
  'executionEnv',
  'extendNodePath',
  'failIfNoMatch',
  'fetchMinSpeedKiBps',
  'fetchRetries',
  'fetchRetryFactor',
  'fetchRetryMaxtimeout',
  'fetchRetryMintimeout',
  'fetchRetryTimeout',
  'fetchTimeout',
  'fetchWarnTimeoutMs',
  'forceLegacyDeploy',
  'frozenLockfile',
  'frozenStore',
  'gitBranchLockfile',
  'gitChecks',
  'gitShallowHosts',
  'globalBinDir',
  'globalDir',
  'globalPnpmfile',
  'globalVirtualStore',
  'globalVirtualStoreDir',
  'hoist',
  'hoistingLimits',
  'hoistPattern',
  'hoistWorkspacePackages',
  'httpProxy',
  'httpsProxy',
  'ignoreCompatibilityDb',
  'ignoredBuiltDependencies',
  'ignoreDeps',
  'ignoreDepScripts',
  'ignoredOptionalDependencies',
  'ignorePatchFailures',
  'ignorePnpmfile',
  'ignoreScripts',
  'ignoreWorkspaceCycles',
  'ignoreWorkspaceRootCheck',
  'includeWorkspaceRoot',
  'injectWorkspacePackages',
  'linkWorkspacePackages',
  'localAddress',
  'lockfile',
  'lockfileDir',
  'lockfileIncludeTarballUrl',
  'loglevel',
  'managePackageManagerVersions',
  'maxsockets',
  'mergeGitBranchLockfiles',
  'mergeGitBranchLockfilesBranchPattern',
  'minimumReleaseAge',
  'minimumReleaseAgeExclude',
  'minimumReleaseAgeExcludePrune',
  'minimumReleaseAgeIgnoreMissingTime',
  'minimumReleaseAgeStrict',
  'modulesCacheMaxAge',
  'modulesDir',
  'namedRegistries',
  'networkConcurrency',
  'neverBuiltDependencies',
  'nodeDownloadMirrors',
  'nodeExperimentalPackageMap',
  'nodeLinker',
  'nodeOptions',
  'nodePackageMapType',
  'nodeVersion',
  'noProxy',
  'noproxy',
  'npmPath',
  'npmrcAuthFile',
  'onlyBuiltDependencies',
  'onlyBuiltDependenciesFile',
  'optimisticRepeatInstall',
  'optional',
  'overrides',
  'packageExtensions',
  'packageImportMethod',
  'packageManagerStrict',
  'packageManagerStrictVersion',
  'patchedDependencies',
  'peerDependencyRules',
  'peersSuffixMaxLength',
  'pmOnFail',
  'pnpmfile',
  'pnpmfileIgnorePkgManifest',
  'pnprServer',
  'preferFrozenLockfile',
  'preferSymlinkedExecutables',
  'preferWorkspacePackages',
  'production',
  'proxy',
  'publicHoistPattern',
  'recursiveInstall',
  'registries',
  'registrySupportsTimeField',
  'requiredScripts',
  'resolutionMode',
  'resolvePeersFromWorkspaceRoot',
  'runtimeOnFail',
  'saveExact',
  'savePrefix',
  'saveWorkspaceProtocol',
  'scriptShell',
  'shamefullyHoist',
  'sharedWorkspaceLockfile',
  'shellEmulator',
  'sideEffectsCache',
  'sideEffectsCacheReadonly',
  'storeDir',
  'strictDepBuilds',
  'strictPeerDependencies',
  'strictSsl',
  'strictStorePkgContentCheck',
  'supportedArchitectures',
  'symlink',
  'syncInjectedDepsAfterScripts',
  'tag',
  'targetDependenciesField',
  'timeout',
  'trustLockfile',
  'trustPolicy',
  'trustPolicyExclude',
  'trustPolicyIgnoreAfter',
  'unsafePerm',
  'update',
  'updateConfig',
  'updateNotifier',
  'useBetaCli',
  'useNodeVersion',
  'useRunningStoreServer',
  'useStderr',
  'verifyDepsBeforeRun',
  'verifyStoreIntegrity',
  'versioning',
  'virtualStoreDir',
  'virtualStoreDirMaxLength',
  'virtualStoreOnly',
  'virtualStoreType',
  'workspaceConcurrency',
]

// Removed in pnpm v11
export const PNPM_V11_REMOVED_SETTINGS: string[] = [
  'allowNonAppliedPatches',
  'executionEnv',
  'ignoreDepScripts',
  'ignorePatchFailures',
  'ignoredBuiltDependencies',
  'managePackageManagerVersions',
  'neverBuiltDependencies',
  'onlyBuiltDependencies',
  'onlyBuiltDependenciesFile',
  'packageManagerStrict',
  'packageManagerStrictVersion',
  'useNodeVersion',
]
